import { useCallback, useEffect, useState } from 'react';
import { api } from '../../api.js';
const formatDate = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';
export default function PharmacistHistory() {
  const [data, setData] = useState([]); const [meta, setMeta] = useState({}); const [page, setPage] = useState(1); const [category, setCategory] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const categories = [['', 'All activity'], ['PRESCRIPTION_REVIEW', 'Prescription reviews'], ['CONSULTATION', 'Consultations'], ['ORDER_REVIEW', 'Order reviews'], ['FOLLOW_UP', 'Follow-ups']];
  const load = useCallback(async () => { setLoading(true); try { const query = new URLSearchParams({ page: String(page), limit: '25', ...(category ? { category } : {}) }); const response = await api(`/api/pharmacist/history?${query}`); setData(response.data.data || []); setMeta(response.data.pagination || {}); setError(''); } catch (err) { setError(err.message || 'Professional history could not be loaded.'); } finally { setLoading(false); } }, [page, category]);
  useEffect(() => { load(); }, [load]);
  return <section className="history-page" aria-label="Professional history"><nav className="history-page__tabs" aria-label="History categories">{categories.map(([value, label]) => <button aria-selected={category === value} className={category === value ? 'is-active' : ''} key={value || 'all'} onClick={() => { setCategory(value); setPage(1); }} type="button">{label}</button>)}</nav><div className="history-toolbar"><span>{loading ? 'Loading activity…' : `${meta.total || 0} activities`}</span><button className="btn btn-primary" onClick={load} type="button">Refresh</button></div>{error && <div className="admin-error" role="alert">{error}</div>}<article className="admin-card history-card">{loading ? <p className="admin-note">Loading your professional history…</p> : data.length === 0 ? <p className="admin-note">You don't have any completed activity in this period.</p> : <div className="history-table-wrap"><table className="history-table"><thead><tr><th>Date & time</th><th>Activity</th><th>Reference</th><th>Resource</th><th>Outcome</th></tr></thead><tbody>{data.map((row) => <tr key={row.id}><td>{formatDate(row.occurredAt)}</td><td>{row.activityType}</td><td>{row.reference || '—'}</td><td>{row.resourceType}</td><td><span className={`history-result is-${row.outcome}`}>{row.outcome}</span></td></tr>)}</tbody></table></div>}<div className="history-pagination"><span>{meta.total || 0} activities</span><div><button disabled={page <= 1 || loading} onClick={() => setPage((value) => value - 1)} type="button">Previous</button><button disabled={page >= (meta.totalPages || 1) || loading} onClick={() => setPage((value) => value + 1)} type="button">Next</button></div></div></article></section>;
}
